/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_TEMA_H_RPCGEN
#define _RPC_TEMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct req_auth_param {
	char *id_clnt;
};
typedef struct req_auth_param req_auth_param;

struct req_auth_resp {
	char *token_resp;
};
typedef struct req_auth_resp req_auth_resp;

struct req_acc_token_param {
	char *id_clnt;
	char *token;
};
typedef struct req_acc_token_param req_acc_token_param;

struct req_acc_token_resp {
	char *token_rers;
	char *token_regen;
	int per_valab;
};
typedef struct req_acc_token_resp req_acc_token_resp;

struct val_del_act_param {
	char *id_clnt;
	char *tip_op;
	char *resursa;
	char *token_rers;
};
typedef struct val_del_act_param val_del_act_param;

struct val_del_act_resp {
	char *mesaj;
};
typedef struct val_del_act_resp val_del_act_resp;

struct app_req_param {
	char *token_rers;
};
typedef struct app_req_param app_req_param;

struct app_req_resp {
	char *token_perm;
};
typedef struct app_req_resp app_req_resp;

#define RPC_TEMA_PROG 135792468
#define RPC_TEMA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Request_Authorization 1
extern  req_auth_resp * request_authorization_1(req_auth_param *, CLIENT *);
extern  req_auth_resp * request_authorization_1_svc(req_auth_param *, struct svc_req *);
#define Request_Access_Token 2
extern  req_acc_token_resp * request_access_token_1(req_acc_token_param *, CLIENT *);
extern  req_acc_token_resp * request_access_token_1_svc(req_acc_token_param *, struct svc_req *);
#define Validate_Delegated_Action 3
extern  val_del_act_resp * validate_delegated_action_1(val_del_act_param *, CLIENT *);
extern  val_del_act_resp * validate_delegated_action_1_svc(val_del_act_param *, struct svc_req *);
#define Approve_Request_Token 4
extern  app_req_resp * approve_request_token_1(app_req_param *, CLIENT *);
extern  app_req_resp * approve_request_token_1_svc(app_req_param *, struct svc_req *);
extern int rpc_tema_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Request_Authorization 1
extern  req_auth_resp * request_authorization_1();
extern  req_auth_resp * request_authorization_1_svc();
#define Request_Access_Token 2
extern  req_acc_token_resp * request_access_token_1();
extern  req_acc_token_resp * request_access_token_1_svc();
#define Validate_Delegated_Action 3
extern  val_del_act_resp * validate_delegated_action_1();
extern  val_del_act_resp * validate_delegated_action_1_svc();
#define Approve_Request_Token 4
extern  app_req_resp * approve_request_token_1();
extern  app_req_resp * approve_request_token_1_svc();
extern int rpc_tema_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_req_auth_param (XDR *, req_auth_param*);
extern  bool_t xdr_req_auth_resp (XDR *, req_auth_resp*);
extern  bool_t xdr_req_acc_token_param (XDR *, req_acc_token_param*);
extern  bool_t xdr_req_acc_token_resp (XDR *, req_acc_token_resp*);
extern  bool_t xdr_val_del_act_param (XDR *, val_del_act_param*);
extern  bool_t xdr_val_del_act_resp (XDR *, val_del_act_resp*);
extern  bool_t xdr_app_req_param (XDR *, app_req_param*);
extern  bool_t xdr_app_req_resp (XDR *, app_req_resp*);

#else /* K&R C */
extern bool_t xdr_req_auth_param ();
extern bool_t xdr_req_auth_resp ();
extern bool_t xdr_req_acc_token_param ();
extern bool_t xdr_req_acc_token_resp ();
extern bool_t xdr_val_del_act_param ();
extern bool_t xdr_val_del_act_resp ();
extern bool_t xdr_app_req_param ();
extern bool_t xdr_app_req_resp ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_TEMA_H_RPCGEN */
