/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_tema.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

req_auth_resp *
request_authorization_1(req_auth_param *argp, CLIENT *clnt)
{
	static req_auth_resp clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Request_Authorization,
		(xdrproc_t) xdr_req_auth_param, (caddr_t) argp,
		(xdrproc_t) xdr_req_auth_resp, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

req_acc_token_resp *
request_access_token_1(req_acc_token_param *argp, CLIENT *clnt)
{
	static req_acc_token_resp clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Request_Access_Token,
		(xdrproc_t) xdr_req_acc_token_param, (caddr_t) argp,
		(xdrproc_t) xdr_req_acc_token_resp, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

val_del_act_resp *
validate_delegated_action_1(val_del_act_param *argp, CLIENT *clnt)
{
	static val_del_act_resp clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Validate_Delegated_Action,
		(xdrproc_t) xdr_val_del_act_param, (caddr_t) argp,
		(xdrproc_t) xdr_val_del_act_resp, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

app_req_resp *
approve_request_token_1(app_req_param *argp, CLIENT *clnt)
{
	static app_req_resp clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Approve_Request_Token,
		(xdrproc_t) xdr_app_req_param, (caddr_t) argp,
		(xdrproc_t) xdr_app_req_resp, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
