/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_tema.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
rpc_tema_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		req_auth_param request_authorization_1_arg;
		req_acc_token_param request_access_token_1_arg;
		val_del_act_param validate_delegated_action_1_arg;
		app_req_param approve_request_token_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Request_Authorization:
		_xdr_argument = (xdrproc_t) xdr_req_auth_param;
		_xdr_result = (xdrproc_t) xdr_req_auth_resp;
		local = (char *(*)(char *, struct svc_req *)) request_authorization_1_svc;
		break;

	case Request_Access_Token:
		_xdr_argument = (xdrproc_t) xdr_req_acc_token_param;
		_xdr_result = (xdrproc_t) xdr_req_acc_token_resp;
		local = (char *(*)(char *, struct svc_req *)) request_access_token_1_svc;
		break;

	case Validate_Delegated_Action:
		_xdr_argument = (xdrproc_t) xdr_val_del_act_param;
		_xdr_result = (xdrproc_t) xdr_val_del_act_resp;
		local = (char *(*)(char *, struct svc_req *)) validate_delegated_action_1_svc;
		break;

	case Approve_Request_Token:
		_xdr_argument = (xdrproc_t) xdr_app_req_param;
		_xdr_result = (xdrproc_t) xdr_app_req_resp;
		local = (char *(*)(char *, struct svc_req *)) approve_request_token_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
