/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_tema.h"

bool_t
xdr_req_auth_param (XDR *xdrs, req_auth_param *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id_clnt, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_auth_resp (XDR *xdrs, req_auth_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_resp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_acc_token_param (XDR *xdrs, req_acc_token_param *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id_clnt, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_req_acc_token_resp (XDR *xdrs, req_acc_token_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_rers, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_regen, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->per_valab))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_val_del_act_param (XDR *xdrs, val_del_act_param *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id_clnt, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tip_op, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resursa, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_rers, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_val_del_act_resp (XDR *xdrs, val_del_act_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->mesaj, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_app_req_param (XDR *xdrs, app_req_param *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_rers, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_app_req_resp (XDR *xdrs, app_req_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_perm, ~0))
		 return FALSE;
	return TRUE;
}
